# Reusable workflow for building and deploying the website
# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: Build And Deploy

on:
  workflow_call:
    inputs:
      branch:
        description: 'If we are in "main" or a "version" docs branch'
        required: true
        type: string
    secrets:
      SAS:
        required: true

jobs:
  build_and_deploy:
    name: Build and deploy the website
    runs-on: ubuntu-latest
    steps:
      - name: Set GIT_BRANCH
        run: echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Print GIT_BRANCH
        run: echo $GIT_BRANCH
      - name: Print content
        run: ls -ln
      - name: Print branch if version
        if: ${{ inputs.branch == 'version' }}
        run: echo ${{ inputs.branch }}
      - name: Print branch if main
        if: ${{ inputs.branch == 'main' }}
        run: echo ${{ inputs.branch }}
      # This should be set up from earlier
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag: v3.3.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # tag: v3.6.0
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@8add8c6d2c8586964896d9fdc639e021312a643f # tag: v1.8.28
      - name: Test
        run: yarn lint && yarn test
        env:
          CI: true
      # FIXME: this is stalling
      # - name: Download cache
      #   uses: nick-invision/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd  # tag: v2.8.3
      #   with:
      #     timeout_seconds: 300
      #     max_attempts: 3
      #     retry_on: error
      #     command: ./scripts/bin/azcopy copy "https://electronwebsite.blob.core.windows.net/%24web/*?$SAS" "./build" --recursive
      #   env:
      #     SAS: ${{ secrets.SAS }}
      - name: Rewrite docs paths if version branch
        if: ${{ inputs.branch == 'version' }}
        run: node scripts/build-as-doc-version.js $(GIT_BRANCH)
      - name: Add Docusaurus problem matcher
        run: echo "::add-matcher::.github/problem-matchers/docusaurus.json"
      - name: Build default locale site
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish "/assets" to Storage if version branch
        if: ${{ inputs.branch == 'version' }}
        uses: nick-invision/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # tag: v2.8.3
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/assets/*" "https://electronwebsite.blob.core.windows.net/%24web/assets?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
      - name: Publish "/docs" to Storage if version branch
        if: ${{ inputs.branch == 'version' }}
        uses: nick-invision/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # tag: v2.8.3
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/docs/*" "https://electronwebsite.blob.core.windows.net/%24web/docs?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
      - name: Publish everything to Storage if main branch
        if: ${{ inputs.branch == 'main' }}
        uses: nick-invision/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # tag: v2.8.3
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/*" "https://electronwebsite.blob.core.windows.net/%24web/?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
